import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import { cn } from "@/lib/utils";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import QueryProvider from "@/providers/query-providers";
import SheetProvider from "@/providers/sheet-provider";
import { Toaster } from "@/components/ui/sonner";

const font = Outfit({ weight: "400", subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(font.className)}
        >
          <header>
            <SignedOut />
            <SignedIn />
          </header>
          <main>
            <QueryProvider>
              <SheetProvider />
              <Toaster />
              {children}
            </QueryProvider>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
